global:
  resolve_timeout: 5m
  smtp_from: 'kangnan1994@163.com' # 发件人
  smtp_smarthost: 'smtp.163.com:25' # 邮箱服务器的 POP3/SMTP 主机配置 smtp.qq.com 端口为 465 或 587
  smtp_auth_username: 'kangnan1994@163.com' # 用户名
  smtp_auth_password: 'EBJDYDAXFWOKUCOT' # 授权码 
  # smtp_require_tls: true
  # smtp_hello: 'xxxx'
templates:
  - '/alertmanager/templates/*.tmpl'
route:
  # group_by: ['conanAlert'] # 告警分组
  group_by: ['alertname','instance']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: all
    receiver: email
    continue: true
    group_wait: 10s
    repeat_interval: 45m
  - match:
      severity: email
    receiver: 'email'
    continue: false
    group_wait: 10s
    repeat_interval: 2h
 
receivers:
- name: 'email'
  email_configs:
  - to: '1837675228@qq.com' # 如果想发送多个人就以 ',' 做分割
    send_resolved: true
    headers: { Subject: '瀚海云告警通知：第三方服务宕机告警'}
    html: '{{ template "custom_mail.html" . }}'   #使用自定义的模板发送
# - name: 'wechat'
#   wechat_configs:
#   - corp_id: 'xxxxxxxxxxxxx' #企业 ID
#     api_url: 'https://qyapi.weixin.qq.com/cgi-bin/' # 企业微信 api 接口 统一定义
#     to_party: '2'  # 通知组 ID
#     agent_id: '1000002' # 新建应用的 agent_id
#     api_secret: 'xxxxxxxxxxxxxx' # 生成的 secret
#     send_resolved: true