groups:
- name: server-down-rule
  rules:
  - alert: ServerDownAlert
    expr: myapp_devices{instance="conanCusGolang", job="myapp"} == 4
    for: 1m
    labels:
      severity: critical
    annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

- name: server-version-rule
  rules:
  - alert: ServerVersionAlert
    expr: myapp_info{instance="conanCusGolang", job="myapp", version="2.10.5", version02="3.1.1", version03="3.1.2", version04="3.1.3"} == 1
    for: 1m
    labels:
      severity: critical
    annotations:
        summary: "job {{ $labels.job }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
