# 全局变量
@host=192.168.1.15
@port=9000
@port2=9001

### Prometheus开发

POST /metrics
Host: {{host}}:{{port}}
Content-Type: application/json
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

